### ISSUE TITLE
Possibly Incorrect AC/DC Table Access

### ISSUE THREAD

**Issue by TarVanimelde** [packjpg/packJPG#12]
The DC tables are accessed with the AC index at

https://github.com/packjpg/packJPG/blob/master/source/packjpg.cpp#L2867

and

https://github.com/packjpg/packJPG/blob/master/source/packjpg.cpp#L2926

I can't find any images where the DC index doesn't equal the AC index, so I can't test if this is intended behaviour.

**Comment by packjpg** [comment]
This is in fact incorrect, and, yes, you will be hard pressed to find any cases where DC index != AC index. If there are even any. I'll fix this.
