### ISSUE TITLE
not compiling anymore

### ISSUE THREAD

**Issue by mausalimi** [packjpg/packJPG#16]
i get lots of error messages.

> x86_64-w64-mingw32-g++ -c -o packjpg.o ..//packJPG//packjpg.cpp -I. -DBUILD_LIB -O3 -Wall -pedantic -funroll-loops -ffast-math -fsched-spec-load -fomit-frame-pointer
..//packJPG//packjpg.cpp: In function 'void pjglib_init_streams(void*, int, int, void*, int)':
..//packJPG//packjpg.cpp:1026:14: error: jump to case label [-fpermissive]

> ..//packJPG//packjpg.cpp:1029:14: error: jump to case label [-fpermissive]

> ..//packJPG//packjpg.cpp:1032:9: error: jump to case label [-fpermissive]

> ..//packJPG//packjpg.cpp:1049:14: error: jump to case label [-fpermissive]

> ..//packJPG//packjpg.cpp:1050:53: error: no match for 'operator=' (operand types are 'std::unique_ptr<Reader>' and 'std::_MakeUniq<MemoryWriter>::__single_object {aka std::unique_ptr<MemoryWriter>}')

>c:\msys64\mingw64\x86_64-w64-mingw32\include\c++\6.2.0\bits\unique_ptr.h:269:2: error: no type named 'type' in 'struct std::enable_if<false, std::unique_ptr<Reader>&>'

>..//packJPG//packjpg.cpp:1053:53: error: no match for 'operator=' (operand types are 'std::unique_ptr<Reader>' and 'std::_MakeUniq<StreamWriter>::__single_object {aka std::unique_ptr<StreamWriter, std::default_delete<StreamWriter> >}')

> ..//packJPG//packjpg.cpp:1055:9: error: jump to case label [-fpermissive]

older versions used to compile fine.

using mingw and gcc 6.3

**Comment by TarVanimelde** [comment]
The compilation issues you listed have been resolved, and I can compile packjpg on mingw on my machine.

**Comment by mausalimi** [comment]
well, it works for packJPG, that's good.

but i wanted to also buils a complete packARC, so i replaced the source in packANY/packJPG with the newer packJPG source.
i can then build the packANYlib.a, but i can't get any further, make -f Makefile_sfx_stub.win fails badly with tons of "undefined reference to...." errors.

so i guess it's not meant to do what i tried. :)
