### ISSUE TITLE
Release download is broken

### ISSUE THREAD

**Issue by tillea** [packjpg/packJPG#19]
I tried to download the tagged release tar.gz / zip.  Both contain only the .gitignore and the LICENSE file.

**Comment by schnaader** [comment]
Works as designed, unfortunately. The release is based on commit a2be395, the initial commit that only contains those two files.

To get an official 2.5k release (both source + binary), use [the developer blog link](http://packjpg.encode.ru/?page_id=17).

Anyway, it should be considered to remove the release if possible as it will only confuse people. Also, adding a 2.5k release would be useful.

**Comment by tillea** [comment]
On Thu, Feb 01, 2018 at 12:23:48AM -0800, Christian Schneider wrote:
> Anyway, it should be considered to remove the release if possible as it will only confuse people.
Yes, its pretty confusing.

> Also, adding a 2.5k release would be useful.
That would be really helpful.  Thanks for the quick reply, Andreas.

**Comment by TarVanimelde** [comment]
Thanks for bringing this to the project's attention, and I apologize for the delayed response. I've compiled and tagged a 2.5k release on the release page. It includes both x86 and x64 Windows binaries (the 64-bit tends to run slightly faster). Happily, it also allowed me to opportunity to correct a misdirected output bug.
