### ISSUE TITLE
Unable to unpack files compressed with 2.3

### ISSUE THREAD

**Issue by ks74** [packjpg/packJPG#21]
I packed an image with XnView (it has packjpg as an addon) and now can't unpack it using the last version of the program.

**Comment by TarVanimelde** [comment]
Different major versions of packJPG are not compatible with each other. 2.3-compressed files will not be decompressable by 2.4 or 2.5, and vice-versa. Iterations of packJPG with the same version number (e.g., 2.3) and different subversions (e.g., 2.3a or 2.3b) will be compatible, however. See https://github.com/packjpg/packJPG/blob/master/docs/versionnumbering.txt
