### ISSUE TITLE
value out of range error: cmp0, frq0, val exceeding limit by 1

### ISSUE THREAD

**Issue by dreamlayers** [packjpg/packJPG#4]
I'm built the latest packJPG from source in Cygwin. Right now it is compressing a large number of photos from an Olympus C-770 Ultra Zoom camera which were already compressed to progressive using jpegoptim built with mozjpeg 3.1. A bunch of files are failing with errors like "P8260278.jpg (value out of range error: cmp0, frq0, val -172, max 171)". All the errors I looked at are exceeding the limit by 1. Seems like this happens to files which have large contrast differences, with some very dark and very bright areas.

[Here is a sample image file.](https://cloud.githubusercontent.com/assets/1137396/20697670/09a69a94-b5c9-11e6-802c-44a348e737ee.jpg) Its SHA1 sum should be 02e12e7dc55ae9c35ac99971c4fc886a41372665.

**Comment by TarVanimelde** [comment]
This is not an error. You will chang
